### ISSUE TITLE
Colours on charts are not the same as on the legends

### ISSUE THREAD

**Issue by olejandro** [Tokni/timesukraine#13]
The colours of the "second" scenario have green shade to distingush it from the first scenario. This seems to be confusing to stakeholders (especially when the original colour + green shade matches a different legend entry). Could the colours for both scenarios be the same?

**Comment by olejandro** [comment]
To make it easy to remember what scenario is where, maybe a concept "red for right" would be useful?

**Comment by olejandro** [comment]
..and lime  or lime green for left?

**Comment by olavurellefsen** [comment]
Fixed with pull request #14
