### ISSUE TITLE
Markdown type

### ISSUE THREAD

**Issue by olejandro** [tokni/timesukraine#38]
Is it possible to use GitLab Flavored Markdown (GFM) instead of the current one? It seems to handle tables and footnotes better (they look nicer).

**Comment by olavurellefsen** [comment]
Check out https://github.com/tokni/timesukraine/pull/42 and https://deploy-preview-42--timesukraine.netlify.com/about

**Comment by olavurellefsen** [comment]
@olejandro Can you be more specific? Both markdown-to-jsx (that we currently use) and react-markdown (that #42 uses) claim to support GFM. See https://probablyup.com/markdown-to-jsx/ and https://rexxars.github.io/react-markdown/, respectively.

**Comment by olejandro** [comment]
It seems that Github flavoured markdown doesn't support footnotes, but Gitlab flavoured one does. 
https://gitlab.com/gitlab-org/gitlab-ce/issues/23171

I've tried additing tables to get them to look similar to https://help.github.com/en/articles/organizing-information-with-tables, but the column and row separation lines don't appear...

**Comment by olavurellefsen** [comment]
Ok, I misread the initial request. You want GitLAB rather than GitHUB flavored markdown. I am having difficulties finding a React package that supports GitLAB flavored markdown. Any suggestions?

**Comment by olejandro** [comment]
It looks really nice now, with the addition of styles! :-)
I can see that the only issue is that footnotes are not supported. Would reverting to the previous version (extended markdown) together with keeping styles solve it all?

**Comment by olavurellefsen** [comment]
Resolved with #45 (return to using markdown-to-jsx)
