### ISSUE TITLE
Disclaimer text

### ISSUE THREAD

**Issue by olejandro** [Tokni/timesukraine#7]
I would like to add a disclaimer text like the following: "The information and results hereby represented are work-in-progress results of “Long-Term Energy Modelling and Forecasting in Ukraine: Scenarios for the Action Plan of Energy Strategy of Ukraine until 2035”, joint project by the MoECI of Ukraine, UDEC and the Danish Energy Agency. The data and results are preliminary, and should not be cited or distributed." Maybe it could be hosted by another welcome box?

**Comment by olavurellefsen** [comment]
Suggested solution in commit 821ccae - Ukrainian translation missing, though
